pool:
  name: Hosted VS2017

steps:
- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: markey'
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption (e7495e6a-6008-49fa-b66c-46709c41acd1)'
    KeyVaultName: markey

- powershell: |
   ls env:
   echo "******************************************manual*************************************"
   
   git clone https://Personal%20Access%20Token:$(pat)@marinaliu.visualstudio.com/Git2/_git/product1
  displayName: 'PowerShell Script'
